/* This source file is generated by 'makedefs'.  Do not edit. */
#define BUILD_DATE "Sun May 22 17:40:10 2016"
#define BUILD_TIME (1463964010L)

#define VERSION_NUMBER 0x03060001UL
#define VERSION_FEATURES 0x00060000UL
#define IGNORED_FEATURES 0x18080000UL
#define VERSION_SANITY1 0x211c517dUL
#define VERSION_SANITY2 0x28a205d0UL
#define VERSION_SANITY3 0x00025000UL

#define VERSION_STRING "3.6.0-1"
#define VERSION_ID \
 "Windows NetHack Beta Version 3.6.0-1 - last build Sun May 22 17:40:10 2016."
#define COPYRIGHT_BANNER_C \
 "         Version 3.6.0-1 Windows Beta, built May 22 17:40:10 2016."

