/* This source file is generated by 'makedefs'.  Do not edit. */
#define BUILD_DATE "Fri May 27 02:54:34 2016"
#define BUILD_TIME (1464342874L)

#define VERSION_NUMBER 0x03060001UL
#define VERSION_FEATURES 0x00060000UL
#define IGNORED_FEATURES 0x18080000UL
#define VERSION_SANITY1 0x211c517dUL
#define VERSION_SANITY2 0xf88195c4UL
#define VERSION_SANITY3 0x00025000UL

#define VERSION_STRING "3.6.0-1"
#define VERSION_ID \
 "Windows NetHack Beta Version 3.6.0-1 - last build Fri May 27 02:54:34 2016."
#define COPYRIGHT_BANNER_C \
 "         Version 3.6.0-1 Windows Beta, built May 27 02:54:34 2016."

